writeText=input('Write Something to Write in File')
fileName=input('Enter File Name')
exampleFile=open(fileName,'a')
exampleFile.write(writeText)
exampleFile.write('\n')
exampleFile.close()
exampleRead=open(fileName,'r').read()
print(exampleRead)
exampleRead2=open(fileName,'r').readlines()
print(exampleRead2)
